[project]
name = "mnotes"
version = "0.1.0"
description = "Personal bleet broadcaster"
readme = "README.rst"
requires-python = ">=3.13"
dependencies = [
    "ciso8601>=2.3.2",
    "feedwerk>=1.2.0",
    "jinja2>=3.1.6",
    "jnrbase>=1.3.0",
    "lxml[cssselect]>=5.4.0",
]
